### ISSUE TITLE
Unable to locate Ghostscript on paths

### ISSUE THREAD

**Issue by NeighborhoodCoding** [Chrispresso/Kaggle-Digit-Recognizer#1]
Hi! I'm using Win10 and python 3.6
I got un error  of "Unable to locate Ghostscript on paths" just after run mnist_number_prediction.py
I tried to install "pip install ghostscript" and i think is is a problem of system path setting for ghostscript app. It is only my error?

-------full error log ------
C:\Users\owner\pyc\Scripts\python.exe C:/Users/owner/Kaggle-Digit-Recognizer-master/mnist_number_guesser.py
2020-06-09 13:20:56.115021: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-06-09 13:21:02.008492: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-06-09 13:21:02.510426: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-06-09 13:21:02.517380: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: INNO-A-957
2020-06-09 13:21:02.517977: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: INNO-A-957
2020-06-09 13:21:02.518386: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\owner\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:/Users/owner/Kaggle-Digit-Recognizer-master/mnist_number_guesser.py", line 68, in reset
    arr = self.canvas_to_ndarray()
  File "C:/Users/owner/Kaggle-Digit-Recognizer-master/mnist_number_guesser.py", line 52, in canvas_to_ndarray
    img = Image.open('tmp_canvas.eps').convert('L')
  File "C:\Users\owner\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 873, in convert
    self.load()
  File "C:\Users\owner\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\EpsImagePlugin.py", line 330, in load
    self.im = Ghostscript(self.tile, self.size, self.fp, scale)
  File "C:\Users\owner\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\EpsImagePlugin.py", line 134, in Ghostscript
    raise OSError("Unable to locate Ghostscript on paths")
OSError: Unable to locate Ghostscript on paths
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\owner\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:/Users/owner/Kaggle-Digit-Recognizer-master/mnist_number_guesser.py", line 68, in reset
    arr = self.canvas_to_ndarray()
  File "C:/Users/owner/Kaggle-Digit-Recognizer-master/mnist_number_guesser.py", line 52, in canvas_to_ndarray
    img = Image.open('tmp_canvas.eps').convert('L')
  File "C:\Users\owner\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 873, in convert
    self.load()
  File "C:\Users\owner\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\EpsImagePlugin.py", line 330, in load
    self.im = Ghostscript(self.tile, self.size, self.fp, scale)
  File "C:\Users\owner\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\EpsImagePlugin.py", line 134, in Ghostscript
    raise OSError("Unable to locate Ghostscript on paths")
OSError: Unable to locate Ghostscript on paths

**Comment by NeighborhoodCoding** [comment]
Oh I just solve it! I just installed Ghostscript and add a installed folder path to a system path..
